// export const userData = [
//   {
//     Id: "CX57HWBexMQhtXgrMEOPAHLX4pb2",
//     name: "Kpodo Winner",
//     username: "meet.winner",
//     course: "Computer Science",
//     profilePhoto: "",
//     bio: '"Here for fun and to make friends. Feel free to add me"',
//     interests: ["Gaming", "Reading", "Travelling"],
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "pHxFg4QNuPS5AqcEXYc228SXlXy2",
//     name: "Nana Agyemang",
//     username: "nana10",
//     course: "Computer Science",
//     profilePhoto: "",
//     bio: "",
//     interests: ["Gaming", "Reading", "Travelling"],
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "m5OqpcsZpTfXJFi6JPUe96KojT72",
//     name: "Worla",
//     username: "nworla_xx",
//     course: "Chemical Enginnering",
//     profilePhoto: "",
//     bio: "",
//     interests: ["Hiking", "Music", "Dance"],
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "FEjKhQ9bz3YZS4eFjvURn59rrfo2",
//     name: "MR. Baah",
//     username: "_baah",
//     course: "Environmental Science",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "E9qKJrQhfXNc6Hy8n1eQIjkV1gw1",
//     name: "Mabel",
//     username: "mabelll",
//     course: "Computer Engineering",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 10,
//     followers: 3000,
//     friends: 30,
//   },
//   {
//     Id: "5",
//     name: "Obaapa Serwaa",
//     username: "serwaaxx",
//     course: "Fashion and Design",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 40,
//     followers: 2980,
//     friends: 45,
//   },
//   {
//     Id: "6",
//     name: "Abraham",
//     username: "father_AB",
//     course: "Chinese",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 300,
//     followers: 1087,
//     friends: 90,
//   },
//   {
//     Id: "Jrm1Yww89UMFl4BpVjCWiRv1Eg93",
//     name: "Aaron",
//     username: "aaron",
//     course: "Literature",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 20,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "8",
//     name: "MR. Agyapong",
//     username: "agyapong",
//     course: "Environmental Science",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "mLrZD7uC1lM341JRjlQq5jUMwNJ2",
//     name: "Elorm Ella",
//     username: "elorm.e",
//     course: "Petroleum Engineering",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 25,
//     followers: 4000,
//     friends: 178,
//   },
//   {
//     Id: "ORq4Crm54sSXQ8Z729qPo4hjpFv2",
//     name: "Godfriend",
//     username: "goddey",
//     course: "Mathematics",
//     profilePhoto: "",
//     bio: "",
//     interests: ["Hiking", "Music", "Dance"],
//     events: 25,
//     followers: 3205,
//     friends: 168,
//   },
//   {
//     Id: "iy58nSPjX1SjcAbtnLAhQymSYyv2",
//     name: "Azu Joshua",
//     username: "_subway",
//     course: "Pharmacy",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 15,
//     followers: 5205,
//     friends: 18,
//   },
//   {
//     Id: "238oqZl5AzOht2fCY5GJHM3TpTD3",
//     name: "Kelvin",
//     username: "savage",
//     course: "Business Administraton",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "0uZRvgU6nANqpQOs7ollhJW2syf2",
//     name: "Tiana",
//     username: "tiana_xx",
//     course: "Marine Engineering",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "UjPX0Qg6OJZm0Z0HJD77d0LiWPz1",
//     name: "Nadine",
//     username: "ms_nadine",
//     course: "Arts",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "15",
//     name: "Francis",
//     username: "franc_",
//     course: "Environmental Science",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "ua6Ads5lOmSuKJxntDzbHySfwrH3",
//     name: "Nicholas",
//     username: "fanta",
//     course: "Electrical Engieering",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 45,
//     followers: 6005,
//     friends: 18,
//   },
//   {
//     Id: "17",
//     name: "Bless",
//     username: "_blessed",
//     course: "Physics",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "18",
//     name: "Eddy",
//     username: "_ed",
//     course: "Environmental Science",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 25,
//     followers: 1205,
//     friends: 178,
//   },
//   {
//     Id: "19",
//     name: "Kwame Young",
//     username: "kwame_y",
//     course: "Political Science",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 5,
//     followers: 55,
//     friends: 78,
//   },
//   {
//     Id: "20",
//     name: "Allan Jackson",
//     username: "AJ",
//     course: "Graphic Design",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 59,
//     followers: 5235,
//     friends: 78,
//   },
//   {
//     Id: "21",
//     name: "Nana Ama",
//     username: "dr.ama",
//     course: "Doctor of Optometry",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 5,
//     followers: 3455,
//     friends: 378,
//   },
//   {
//     Id: "22",
//     name: "David Baah",
//     username: "coder",
//     course: "Computer Science",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 5,
//     followers: 55,
//     friends: 78,
//   },
//   {
//     Id: "23",
//     name: "Jack Jackson",
//     username: "jack_jack",
//     course: "Biological Science",
//     profilePhoto: "",
//     bio: "",
//     interests: "",
//     events: 65,
//     followers: 285,
//     friends: 378,
//   },
// ];

export const userData = [
  {
    Id: "pkTHtmnWjWMvnDSfqTruVBjWEZx2",
    name: "Kpodo Winner",
    username: "meet.winner",
    gender: "Male",
    course: "Computer Science",
    profilePhoto: require("./assets/winner.jpg"),
    bio: '"Here for fun and to make friends. Feel free to add me"',
    interests: ["Gaming", "Reading", "Travelling"],
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "t4KNqWmVcOZ3x6Sepvov55LHl2y2",
    name: "Mabel",
    username: "mabelll",
    gender: "Female",
    course: "Computer Engineering",
    profilePhoto: require("./assets/mabel.jpeg"),
    bio: "🥀",
    interests: ["Dancing", "Movies", "Travelling"],
    events: 10,
    followers: 3000,
    friends: 30,
  },
];

export const posts = [
  {
    Id: "1",
    username: "Winner",
    userProfile: require("./assets/prof.jpg"),
    postType: "Friend",
    time: "30mins ago",
    caption: "Come with me to the Grace crusade this Sunday and be blessed 😇",
    img: require("./assets/church.jpg"),
  },
  {
    Id: "2",
    username: "Agyemang",
    userProfile: require("./assets/prof.jpg"),
    postType: "Public",
    time: "2hours ago",
    caption:
      "Exams is just around the corner. Please come with me to the tutorial at the library tomorrow",
    img: require("./assets/library.jpg"),
  },
  {
    Id: "3",
    username: "Mabel",
    userProfile: require("./assets/prof.jpg"),
    postType: "Friends",
    time: "3hours ago",
    caption:
      "My birthday is this Saturday. Who would like to go on a date with me 👉👈😩",
    img: require("./assets/date.jpg"),
  },
  {
    Id: "4",
    username: "Savage",
    userProfile: require("./assets/prof.jpg"),
    postType: "Public",
    time: "1day ago",
    caption:
      "Hey boys and girls, forget exams. Party dey town this Friday. Come let's chill. #YOLO😜",
    img: require("./assets/club.jpg"),
  },
];
