export const userData = [
  {
    Id: "CX57HWBexMQhtXgrMEOPAHLX4pb2",
    name: "Kpodo Winner",
    username: "meet.winner",
    course: "Computer Science",
    profilePhoto: "",
    bio: '"Here for fun and to make friends. Feel free to add me"',
    interests: ["Gaming", "Reading", "Travelling"],
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "pHxFg4QNuPS5AqcEXYc228SXlXy2",
    name: "Nana Agyemang",
    username: "nana10",
    course: "Computer Science",
    profilePhoto: "",
    bio: "",
    interests: ["Gaming", "Reading", "Travelling"],
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "m5OqpcsZpTfXJFi6JPUe96KojT72",
    name: "Worla",
    username: "nworla_xx",
    course: "Chemical Enginnering",
    profilePhoto: "",
    bio: "",
    interests: ["Hiking", "Music", "Dance"],
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "FEjKhQ9bz3YZS4eFjvURn59rrfo2",
    name: "MR. Baah",
    username: "_baah",
    course: "Environmental Science",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "sEP2v3q29GdQV5Ftu0j8vEdNvrt1",
    name: "Mabel",
    username: "mabelll",
    course: "Computer Engineering",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 10,
    followers: 3000,
    friends: 30,
  },
  {
    Id: "5",
    name: "Obaapa Serwaa",
    username: "serwaaxx",
    course: "Fashion and Design",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 40,
    followers: 2980,
    friends: 45,
  },
  {
    Id: "6",
    name: "Abraham",
    username: "father_AB",
    course: "Chinese",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 300,
    followers: 1087,
    friends: 90,
  },
  {
    Id: "Jrm1Yww89UMFl4BpVjCWiRv1Eg93",
    name: "Aaron",
    username: "aaron",
    course: "Literature",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 20,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "8",
    name: "MR. Agyapong",
    username: "agyapong",
    course: "Environmental Science",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "mLrZD7uC1lM341JRjlQq5jUMwNJ2",
    name: "Elorm Ella",
    username: "elorm.e",
    course: "Petroleum Engineering",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 4000,
    friends: 178,
  },
  {
    Id: "ORq4Crm54sSXQ8Z729qPo4hjpFv2",
    name: "Godfriend",
    username: "goddey",
    course: "Mathematics",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 3205,
    friends: 168,
  },
  {
    Id: "iy58nSPjX1SjcAbtnLAhQymSYyv2",
    name: "Azu Joshua",
    username: "_subway",
    course: "Pharmacy",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 15,
    followers: 5205,
    friends: 18,
  },
  {
    Id: "zqGaB4ahauhUfwbs6LlMI7iIwji2",
    name: "Kelvin",
    username: "savage",
    course: "Business Administraton",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "0uZRvgU6nANqpQOs7ollhJW2syf2",
    name: "Tiana",
    username: "tiana_xx",
    course: "Marine Engineering",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "UjPX0Qg6OJZm0Z0HJD77d0LiWPz1",
    name: "Nadine",
    username: "ms_nadine",
    course: "Arts",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "15",
    name: "Francis",
    username: "franc_",
    course: "Environmental Science",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "16",
    name: "Nicholas",
    username: "fanta",
    course: "Electrical Engieering",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 45,
    followers: 6005,
    friends: 18,
  },
  {
    Id: "17",
    name: "Bless",
    username: "_blessed",
    course: "Physics",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "18",
    name: "Eddy",
    username: "_ed",
    course: "Environmental Science",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 25,
    followers: 1205,
    friends: 178,
  },
  {
    Id: "19",
    name: "Kwame Young",
    username: "kwame_y",
    course: "Political Science",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 5,
    followers: 55,
    friends: 78,
  },
  {
    Id: "20",
    name: "Allan Jackson",
    username: "AJ",
    course: "Graphic Design",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 59,
    followers: 5235,
    friends: 78,
  },
  {
    Id: "21",
    name: "Nana Ama",
    username: "dr.ama",
    course: "Doctor of Optometry",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 5,
    followers: 3455,
    friends: 378,
  },
  {
    Id: "22",
    name: "David Baah",
    username: "coder",
    course: "Computer Science",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 5,
    followers: 55,
    friends: 78,
  },
  {
    Id: "23",
    name: "Jack Jackson",
    username: "jack_jack",
    course: "Biological Science",
    profilePhoto: "",
    bio: "",
    interests: "",
    events: 65,
    followers: 285,
    friends: 378,
  },
];
