const userData = [
  {
    1: {
      Id: "1",
      name: "Kpodo Winner",
      username: "meet.winner",
      course: "Computer Science",
      profilePhoto: "",
      bio: "Here for fun and to make friends. Feel free to add me",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    2: {
      Id: "2",
      name: "Nana Agyemang",
      username: "nana10",
      course: "Computer Science",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    3: {
      Id: "3",
      name: "MR. Baah",
      username: "_baah",
      course: "Environmental Science",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    4: {
      Id: "4",
      name: "Mabel",
      username: "mabelll",
      course: "Computer Engineering",
      profilePhoto: "",
      bio: "",
      events: 10,
      followers: 3000,
      friends: 30,
    },
    5: {
      Id: "5",
      name: "Obaapa Serwaa",
      username: "serwaaxx",
      course: "Fashion and Design",
      profilePhoto: "",
      bio: "",
      events: 40,
      followers: 2980,
      friends: 45,
    },
    6: {
      Id: "6",
      name: "Abraham",
      username: "father_AB",
      course: "Chinese",
      profilePhoto: "",
      bio: "",
      events: 300,
      followers: 1087,
      friends: 90,
    },
    7: {
      Id: "7",
      name: "Aaron",
      username: "aaron",
      course: "Literature",
      profilePhoto: "",
      bio: "",
      events: 20,
      followers: 1205,
      friends: 178,
    },
    8: {
      Id: "8",
      name: "MR. Agyapong",
      username: "agyapong",
      course: "Environmental Science",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    9: {
      Id: "9",
      name: "Elorm Ella",
      username: "elorm.e",
      course: "Petroleum Engineering",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 4000,
      friends: 178,
    },
    10: {
      Id: "10",
      name: "Godfriend",
      username: "goddey",
      course: "Mathematics",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 3205,
      friends: 168,
    },
    11: {
      Id: "11",
      name: "Azu Joshua",
      username: "_subway",
      course: "Pharmacy",
      profilePhoto: "",
      bio: "",
      events: 15,
      followers: 5205,
      friends: 18,
    },
    12: {
      Id: "12",
      name: "Kelvin",
      username: "savage",
      course: "Business Administraton",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    13: {
      Id: "13",
      name: "Tiana",
      username: "tiana_xx",
      course: "Marine Engineering",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    14: {
      Id: "14",
      name: "Nadine",
      username: "ms_nadine",
      course: "Arts",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    15: {
      Id: "15",
      name: "Francis",
      username: "franc_",
      course: "Environmental Science",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    16: {
      Id: "16",
      name: "Nicholas",
      username: "fanta",
      course: "Electrical Engieering",
      profilePhoto: "",
      bio: "",
      events: 45,
      followers: 6005,
      friends: 18,
    },
    17: {
      Id: "17",
      name: "Bless",
      username: "_blessed",
      course: "Physics",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    18: {
      Id: "18",
      name: "Eddy",
      username: "_ed",
      course: "Environmental Science",
      profilePhoto: "",
      bio: "",
      events: 25,
      followers: 1205,
      friends: 178,
    },
    19: {
      Id: "19",
      name: "Kwame Young",
      username: "kwame_y",
      course: "Political Science",
      profilePhoto: "",
      bio: "",
      events: 5,
      followers: 55,
      friends: 78,
    },
    20: {
      Id: "20",
      name: "Allan Jackson",
      username: "AJ",
      course: "Graphic Design",
      profilePhoto: "",
      bio: "",
      events: 59,
      followers: 5235,
      friends: 78,
    },
    21: {
      Id: "21",
      name: "Nana Ama",
      username: "dr.ama",
      course: "Doctor of Optometry",
      profilePhoto: "",
      bio: "",
      events: 5,
      followers: 3455,
      friends: 378,
    },
    22: {
      Id: "22",
      name: "David Baah",
      username: "coder",
      course: "Computer Science",
      profilePhoto: "",
      bio: "",
      events: 5,
      followers: 55,
      friends: 78,
    },
    23: {
      Id: "23",
      name: "Jack Jackson",
      username: "jack_jack",
      course: "Biological Science",
      profilePhoto: "",
      bio: "",
      events: 65,
      followers: 285,
      friends: 378,
    },
  },
];
